<div style="position:absolute; right: 30px; top: 10px;">
	<a href="http://www.dotnetnuke.com/DesktopModules/Admin/Banners/BannerClickThrough.aspx?BannerId=1447&VendorId=55"><img src="http://www.dotnetnuke.com/LinkClick.aspx?fileticket=FXDN9BAyGSE%3d&tabid=1123&mid=6189" alt="Give Your Feedback in the DotNetNuke Beta Forums!" /></a>
</div>
<script>
  jQuery(function($){
  	$('.logo_pad').css("position", "relative");
  });
</script>